version: "3.7"

networks:
  tbot-network:
    name: tbot-network
#    external: true
  tbot-proxy.network:
    name: tbot-proxy.network
#    external: true

services:
  tbot-app:
    container_name: tbot-app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - tbot-mysql
      - tbot-redis
    env_file:
      - .env
    volumes:
      - ./:/app:cached
    extra_hosts:
      - "host.docker.internal:host-gateway" #for xDebug
    networks:
      - tbot-network

  tbot-app-nginx:
    container_name: tbot-app-nginx
    build:
      context: ./docker/nginx
    depends_on:
      - tbot-app
    volumes:
      - ./public:/app/public:cached
    networks:
      - tbot-network
      - tbot-proxy.network
    labels:
      - traefik.enable=true
      - traefik.http.routers.tbot-nginx.rule=Host(`tbot.localhost`)

  tbot-redis:
    container_name: tbot-redis
    build:
      context: ./docker/redis
    command: redis-server --appendonly yes
    hostname: "redis"
    volumes:
      - tbot-redis-storage:/data
    networks:
      - tbot-network
      - tbot-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.tbot-redis.loadBalancer.server.port=6379
      - traefik.tcp.routers.tbot-redis.entrypoints=redis
      - traefik.tcp.routers.tbot-redis.rule=HostSNI(`*`)
      - traefik.tcp.routers.tbot-redis.service=tbot-redis

  tbot-mysql:
    container_name: tbot-mysql
    build:
      context: ./docker/mysql
    volumes:
      - tbot-mysql-storage:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - tbot-network
      - tbot-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.tbot-mysql.loadBalancer.server.port=3306
      - traefik.tcp.routers.tbot-mysql.entrypoints=mysql
      - traefik.tcp.routers.tbot-mysql.rule=HostSNI(`*`)
      - traefik.tcp.routers.tbot-mysql.service=tbot-mysql

  tbot-rabbit:
    container_name: tbot-rabbit
    build:
      context: ./docker/rmq
    volumes:
      - tbot-rabbit-storage:/var/lib/rabbitmq
    networks:
      - tbot-network
      - tbot-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.tbot-rabbit.loadBalancer.server.port=5672
      - traefik.tcp.routers.tbot-rabbit.entrypoints=rabbit
      - traefik.tcp.routers.tbot-rabbit.rule=HostSNI(`*`)
      - traefik.tcp.routers.tbot-rabbit.service=tbot-rabbit

  tbot-proxy:
    container_name: tbot-proxy
    image: traefik:v2.5
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=tbot-proxy.network
      - --providers.docker.useBindPortIP=false
      - --entrypoints.web.address=:80
      - --entrypoints.redis.address=:6379
      - --entrypoints.mysql.address=:3306
      - --entrypoints.rabbit.address=:5672
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "6379:6379"
      - "3306:3306"
      - "5672:5672"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tbot-proxy.network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`tbot-proxy.localhost`)"
      - "traefik.http.routers.api.service=api@internal"

volumes:
  tbot-redis-storage:
  tbot-mysql-storage:
  tbot-rabbit-storage:
